import React from "react";
import Head from "next/head";
import TodoList from "@components/Todo/TodoList";
import Layout from "@components/Layout";
import CreateTodoForm from "@components/Form/CreateTodoForm";
import AuthHoc from "@components/AuthHOC";

export default function Page() {
  return (
    <>
      <Head>
        <title>Wanted challenge</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <CreateTodoForm />
        <TodoList />
      </main>
    </>
  );
}

Page.getLayout = function getLayout(page: React.ReactElement) {
  return (
    <AuthHoc>
      <Layout>{page}</Layout>
    </AuthHoc>
  );
};
